# Generated by Django 5.2.7 on 2025-11-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('color', models.CharField(help_text='Ex: #FF5733', max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('desc', models.TextField(help_text='Breve descrição para o card', verbose_name='Resumo')),
                ('content', models.TextField(help_text='Texto completo da notícia, pode conter h1, h2, etc.', verbose_name='Conteúdo principal')),
                ('img', models.ImageField(upload_to='news_images/', verbose_name='Imagem')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-date'],
            },
        ),
    ]
