# Generated by Django 5.2.7 on 2025-11-15 17:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Ex: #FF5733', image_field=None, max_length=7, samples=None, verbose_name='Cor (hex)'),
        ),
    ]
