# Generated by Django 5.2.7 on 2025-11-19 21:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Texto completo da notícia', verbose_name='Conteúdo principal'),
        ),
    ]
