# Generated by Django 5.2.7 on 2025-11-20 17:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20251120_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Texto completo da notícia', verbose_name='Conteúdo principal'),
        ),
    ]
