# Generated by Django 5.2.7 on 2025-11-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_principal', models.CharField(help_text='Cor principal do site em formato hexadecimal (ex: #3498db)', max_length=7)),
            ],
        ),
    ]
