# Generated by Django 5.2.7 on 2025-11-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='cor_principal',
            field=models.CharField(default='#3498db', help_text='Cor principal do site em formato hexadecimal (ex: #3498db)', max_length=7),
        ),
    ]
