# Generated by Django 5.2.7 on 2025-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_configuracaosite_cor_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='logo',
            field=models.ImageField(blank=True, help_text='Envie a logo do site', null=True, upload_to='logos/'),
        ),
    ]
