# Generated by Django 5.2.7 on 2025-11-15 17:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaosite_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='cor_principal',
            field=colorfield.fields.ColorField(default='#3498db', help_text='Cor principal do site em formato hexadecimal (ex: #3498db)', image_field=None, max_length=7, samples=None),
        ),
    ]
