# Generated by Django 5.2.7 on 2025-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracaosite_cor_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='position_player',
            field=models.CharField(choices=[('top', 'No topo do site'), ('bottom', 'na parte de baixo do site'), ('right', 'Na lateral direita do site')], default='top', help_text='Posição do player de música na tela', max_length=10),
        ),
    ]
