# Generated by Django 5.2.7 on 2025-11-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_configuracaosite_position_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='position_player',
            field=models.CharField(choices=[('top', 'No topo do site'), ('bottom', 'Na parte de baixo do site')], default='top', help_text='Posição do player de música na tela', max_length=11, verbose_name='Posição do player'),
        ),
    ]
