# Generated by Django 5.2.7 on 2025-11-18 17:55

import carrosel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrosel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=120)),
                ('imagem', models.ImageField(upload_to='carrossel/', validators=[carrosel.models.validar_tamanho])),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
