# Generated by Django 5.2.7 on 2025-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(choices=[(1, 'Top 1'), (2, 'Top 2'), (3, 'Top 3'), (4, 'Top 4'), (5, 'Top 5'), (6, 'Top 6'), (7, 'Top 7'), (8, 'Top 8'), (9, 'Top 9'), (10, 'Top 10')], help_text='Escolha a posição no ranking (1 a 10)', unique=True)),
                ('artista', models.CharField(max_length=100)),
                ('musica', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='top10/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top 10 Música',
                'verbose_name_plural': 'Top 10 Músicas',
                'ordering': ['posicao'],
            },
        ),
    ]
